# Setup
title: UniverSR Demo
tagline: ICASSP 2026
url: https://woongzip1.github.io
baseurl: "/universr-demo"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - Gemfile.bak
  - Gemfile.lock.bak
  - LICENSE.md
  - README.md
  - poole-for-jekyll.gemspec

sass:
  sass_dir: _sass
  style: :compressed

# Author
author:
  name: Woongjib Choi
  url: https://woongzip1.github.io
